config/routes.rb
Rails.application.routes.draw do
  # get 'todo_lists/edit'

  # get 'todo_lists/create'

  root 'notes#index'

  resources :notes do
    resources :todo_lists do
      member do
        patch :complete
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :todo_lists, dependent: :destroy

  scope :asc_order, -> { order("created_at DESC") }

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :note

  scope :sorted, -> { order("created_at ASC") }

  validates_presence_of :content

  def completed?
    !completed_at.blank?
  end

  def toggle_completion
    if completed?
      update_attribute(:completed_at, nil)
    else
      update_attribute(:completed_at, Time.now)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # before_action :authenticate_user!
  # before_action :find_note_category
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.asc_order
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @todo_list = @note.todo_lists.sorted
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_note
  before_action :set_todo_list, except: [:create]

  def create
    @todo_list = @note.todo_lists.create(todo_list_params)
    if @todo_list.save
      redirect_to @note
    else
      redirect_to :back, notice: 'New todo item was not successfully created'
    end
  end

  def destroy
    @todo_list.destroy
    redirect_to @note
  end

  # toggle_completion def => models/todo_list.rb
  def complete
    @todo_list.toggle_completion
    redirect_to @note
  end

  private

  def set_note
    @note = Note.friendly.find(params[:note_id])
  end

  def set_todo_list
    @todo_list = @note.todo_lists.find(params[:id])
  end

  def todo_list_params
    params.require(:todo_list).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notepad</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
      <div class="clearfix"></div>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, class: 'label' %>
    <%= f.text_field :title, placeholder: "Note title", class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description, class: 'label' %>
    <%= f.text_area :description, rows: '5', class: 'form-control resize-dis' %>
  </div>

  <div class="form-btn">
    <%= f.submit class: 'btn-control' %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="title">
  <h1>Editing Note</h1>
</div>

<%= render 'form', note: @note %>

<div class="form-btn">
  <%= link_to 'Show', @note, class: 'btn-control' %>
  <%= link_to 'Back', notes_path, class: 'btn-control' %>
</div>

app/views/notes/index.html.erb
<div class="title">
  <h1>Todo Notes</h1>
</div>
<div class="notice-info">
  <p id="notice"><%= notice %></p>
</div>

<div class="actions">
  <%= link_to 'Add New Note', new_note_path %>
</div>

<table class="table">
  <thead>
    <tr>
      <th class="table-header">Title</th>
      <th class="table-header">Description</th>
      <th class="table-header">Tasks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td class="table-data"><%= link_to note.title, note_path(note) %></td>
        <td class="table-data"><%= truncate(note.description, :leghth => 10) %></td>
        <td class="table-data"><%= note.todo_lists.count %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notes/new.html.erb
<div class="title">
  <h1>New Note</h1>
</div>

<%= render 'form', note: @note %>

<div class="form-btn">
  <%= link_to 'Back', notes_path, class: 'btn-control' %>
</div>

app/views/notes/show.html.erb
<div class="notice-info">
  <p id="notice"><%= notice %></p>
</div>
<div class="title">
  <h1>
    <%= @note.title %>
  </h1>
</div>
<div class="description">
  <p>
    <%= @note.description %>
  </p>
</div>
<div class="actions">
  <%= link_to 'Edit', edit_note_path(@note) %>
  <%= link_to 'Back', notes_path %>
</div>
<div class="num-items">
  <h2><%= @note.todo_lists.count %> items</h2>
</div>

<div class="list">
  <%= render @note.todo_lists %>
</div>

<div class="list-form">
  <%= render 'todo_lists/form' %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for([@note, @note.todo_lists.build]) do |f| %>
  <%= f.text_field :content, autofocus: true, placeholder: "Enter your list item here...", class: 'item-text-field' %>
  <%= f.submit "Enter", class: 'btn-submit' %>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<% if todo_list.completed? %>
<div class="todo-list-item">
  <ul>
    <li><strike><%= link_to todo_list.content, complete_note_todo_list_path(@note, todo_list.id), method: :patch %></strike></li>
  </ul>
</div>
<div class="actions icon-trash">
  <%= link_to "delete", note_todo_list_path(@note, todo_list.id), method: :delete, data: { confirm: "Are you sure?" } %>
</div>
<% else %>
<div class="todo-list-item">
  <ul>
    <li><%= link_to todo_list.content, complete_note_todo_list_path(@note, todo_list.id), method: :patch %></li>
  </ul>
</div>
<div class="actions icon-trash">
  <%= link_to "delete", note_todo_list_path(@note, todo_list.id), method: :delete, data: { confirm: "Are you sure?" } %>
</div>
<% end %>